### ISSUE TITLE
安装出现错误

### ISSUE THREAD

**Issue by 555me** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#1]
如题与图，安装出现错误。
win10的谷歌浏览器。
![屏幕截图 2021-04-25 162505](https://user-images.githubusercontent.com/83159590/115986500-0aa9ee00-a5e3-11eb-93b5-9de948db758b.jpg)

**Comment by lwt-414** [comment]
你下载的是从上往下数的第三个名为“Source code(zip)”的包吗？
那个是源代码，还没有编译过的。
请下载第二个“Dun-Cookie-2.0.28.zip”的包噢
顺便一提，可以下载[v2.0.30](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/releases/tag/2.0.30)的版本了,加入泰拉记事社微博的饼

**Comment by lwt-414** [comment]
请问一下有收到吗，如果ok了还麻烦回复一下 我好关闭issue

**Comment by 555me** [comment]
啊 早就可以关啦&nbsp; &nbsp;问完三天没有问题基本上就是搞定了&nbsp; 谢谢谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 凌晨0:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue] 安装出现错误 (#1)





 
请问一下有收到吗，如果ok了还麻烦回复一下 我好关闭issue

**Comment by lwt-414** [comment]
好的好的 怕没有收到
