### ISSUE TITLE
更新时无法覆盖安装

### ISSUE THREAD

**Issue by Yjun233** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#2]
![image](https://user-images.githubusercontent.com/67272072/118427725-796cf980-b700-11eb-83ff-41e9248fe1b1.png)
Chrome商店也不提示有更新。要么删了重装，要么装了再删，还得重新改一遍设置。
（用的360极速浏览器）

**Comment by LiuZiYang1** [comment]
Chrome不会主动提示更新 它只会隔几个小时悄悄给你更新了，你可也以在 chrome://extensions/ 中点击更新来更新

然后重装其实就是把你的加载的文件夹文件覆盖掉就行了，然后在Chrome管理插件的地方点击
![image](https://user-images.githubusercontent.com/22094581/118617831-96372900-b7f5-11eb-88e3-420a557171c8.png)
来刷新


然后我们的新版本现在添加了个设置导入导出的功能来适应你的重装改设置的问题
