### ISSUE TITLE
建议优化一下游戏内公告弹窗通知的逻辑

### ISSUE THREAD

**Issue by Yjun233** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#22]
现在是只要会弹窗就一定会通知一次，但很多时候弹窗的时候新公告已经出来了，这其实没必要提醒有弹窗，直接看公告就行了。
我们真正需要弹窗通知的情况其实是置顶了一个不存在的公告id，这时候才有蹲饼的价值。
所以建议优化成当focusAnnounceId更新时，announceList中没有对应的id值时才会通知有弹窗。

**Comment by lwt-414** [comment]
已改[9e0edf3](9e0edf3adec76375e3b6f5bcadd8a66053fc52b4)，下个版本更新的时候采用新的逻辑
