### ISSUE TITLE
消息推送Bug反馈

### ISSUE THREAD

**Issue by FranceAir** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#25]
![image](https://user-images.githubusercontent.com/71385614/132948968-52a22103-9f1c-4353-8b22-c9ab9ee6b6ac.png)
不知道为什么，升级到3.0之后，每次开电脑都会给我推送这个信息，是什么bug吗？

**Comment by lwt-414** [comment]
2.9.5新增的重要推送，一般推送一些重要消息，改变接口导致的插件崩溃或者想这次的宣发公告
这个公告只设置了10号和11号两天的推送，明天就没推了
