### ISSUE TITLE
Firefox 每次打开扩展都会显示：窗口太小,可能显示出现问题

### ISSUE THREAD

**Issue by breathiness** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#27]
虽然出现了提示，但是点进去后画面并没有太大的异常。  
有没有方法可以取消该提示？

![Snipaste_2021-09-23_16-49-30](https://user-images.githubusercontent.com/11361630/134479754-00bef262-410d-4162-9443-dbeab2f0817d.png)

**Comment by Yun-Shan** [comment]
是手机版吗

**Comment by breathiness** [comment]
电脑版的，系统是 Windows 10 专业版 20H2

**Comment by Yun-Shan** [comment]
请问这个界面是在怎样打开的，我在firefox上好像看不到这样的界面(指左上角有一个返回按钮

**Comment by breathiness** [comment]
直接点击扩展按钮就出来了，样式不一样可能是因为我使用了 userChrome 的原因。

<https://github.com/muckSponge/MaterialFox>

![图片](https://user-images.githubusercontent.com/11361630/134503375-aacd084d-e833-4ef5-a51e-582694ec5b32.png)

**Comment by breathiness** [comment]
但是应该不是这个原因。同样有类似窗口的其他扩展都是没有这样的情况的。  
比如暴力猴、哔哩哔哩助手、Bitwarden。这几款都不会出现这种情况。

**Comment by Yun-Shan** [comment]
了解了，作为一个临时的解决办法，可以点这个把图标移出来就可以了
![image.png](https://i.loli.net/2021/09/23/RcSIqCfJw43mbHs.png)
我们会尽快修复这个问题

**Comment by breathiness** [comment]
好的，谢谢♥

**Comment by lwt-414** [comment]
如果喜欢将插件放于折叠处的话，建议先将插件移出折叠，进入二级菜单然后设置，在界面设置中改成窗口化显示，再将插件图标折叠。之后点击插件图标后会以窗口模式打开，才不会造成界面样式变形
