### ISSUE TITLE
Do you plan to make a Visual Studio Code extension that awaits Hypergryph's cookies?

### ISSUE THREAD

**Issue by septsea** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#30]
Do you plan to make a Visual Studio Code extension that awaits Hypergryph's cookies?

您打算作一个等鹰角的饼的视觉工作室代码插件吗？

---

Dear developers,

亲爱的开发人：

I feel so pleased that you developed such a great tool. It is really useful. Do you plan to bring the reminder to one of the most popular text editors, Visual Studio Code? It will be more convenient for me because I spend most of my time in typing and I do not really need an Internet browser when I am busy with work.

您作出这样的工具来，我很高兴。它确实有用。您打算把这个提醒器带到流行的文本编辑器，视觉工作室代码吗？因为我花大部分时间在打字上，而且我忙的时候不需要开互联网浏览器，所以一个视觉代码工作室插件对我而言更方便一些。

Look forward to your reply.

期待您的回复。

Sincerely Yours,

Septsea

谨启

纳纳米

**Comment by lwt-414** [comment]
Hello, thank you for contacting us.
We do not have experience developing extension in VScode yet. In addition, VScode is not suitable to for display complex interface and popovers.
You can try to use Chrome or Edge and open their `Continue running background extensions and apps when (Microsoft Edge\Google Chrome) is closed`. Then, you can receive popup notifications even if you don't open your browser.

**Comment by septsea** [comment]
@lwt-414 Thanks for your reply.

I see. If that is the situation, I will consider migrating to Edge.

I will close the issue.

**Comment by lwt-414** [comment]
What browser are you using now?

**Comment by septsea** [comment]
@lwt-414 I am using Firefox Nightly.

**Comment by lwt-414** [comment]
Firefox has not "background running". Maybe you can try install ceobe canteen in Edge. If it has popup notification and you want to see it, then open browser and list of ceobe canteen to see it.

**Comment by septsea** [comment]
@lwt-414 Thanks for your advice.
