### ISSUE TITLE
如果能添加快捷方式打开就更棒了

### ISSUE THREAD

**Issue by DeaneCanaan** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#31]
扩展装的太多。。。每次想打开还得找一下。。
如果能有键盘快捷键打开就好了（如果可行的话）
=。=

**Comment by lwt-414** [comment]
请问你是什么浏览器呢

**Comment by lwt-414** [comment]
这个是自己设置的噢，在地址栏输入设置
chrome浏览器：`chrome://extensions/shortcuts`
edge浏览器： `edge://extensions/shortcuts`
火狐浏览器：`about:addons`  >  管理你的扩展旁边有个齿轮设置 > 管理扩展快捷键

**Comment by DeaneCanaan** [comment]
> 这个是自己设置的噢，在地址栏输入设置 chrome浏览器：`chrome://extensions/shortcuts` edge浏览器： `edge://extensions/shortcuts` 火狐浏览器：`about:addons` > 管理你的扩展旁边有个齿轮设置 > 管理扩展快捷键

3Q
