### ISSUE TITLE
蹲饼器主面板老是连不上接口

### ISSUE THREAD

**Issue by Yanstory** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#32]
![image](https://user-images.githubusercontent.com/5153875/145531591-cf6a48cf-ac3e-483c-af0b-262948a88d2d.png)
![image](https://user-images.githubusercontent.com/5153875/145531513-d1e6cc0e-9ef9-465d-9b5a-8fad1a3b92eb.png)
大多数时候都是这种情况，但消息提醒照常弹出

**Comment by lwt-414** [comment]
方便主页面滑到第二个那边我看看吗

**Comment by Yanstory** [comment]
2~3屏：
![image](https://user-images.githubusercontent.com/5153875/145533809-e8b374e7-c851-4b32-aaa3-c8110d12a8bd.png)
![image](https://user-images.githubusercontent.com/5153875/145533857-69932a05-3d7c-49ac-bfea-e10c63072ea8.png)
（奇妙的是刚想写连接成功一会儿发就这样了）

**Comment by lwt-414** [comment]
你有正常的获取到主页这个接口过吗

**Comment by Yanstory** [comment]
有过，卡池、活动信息、视频传送门和时间线内容能正常加载
连不上接口的时候主面板就不会更新了，但还能弹最新的消息通知

**Comment by lwt-414** [comment]
如果方便的话，看看加个群？我可能需要远程控制看看接口获取是不是正常
