### ISSUE TITLE
打开大图时显示的一直是旧的图片

### ISSUE THREAD

**Issue by breathiness** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#33]
不管点击哪张图片，显示的一直是卡达的图。
![动画](https://user-images.githubusercontent.com/11361630/146335114-da862b86-fc9f-4342-a667-e2f1165c5487.gif)

**Comment by lwt-414** [comment]
一直都这样子吗，我们这边还没有人反馈过这个bug，能麻烦加群我们详细了解一下吗
顺便建议移出折叠，界面才会正常显示噢

**Comment by lwt-414** [comment]
> 一直都这样子吗，我们这边还没有人反馈过这个bug，能麻烦加群我们详细了解一下吗

**Comment by breathiness** [comment]
> 



> 一直都这样子吗，我们这边还没有人反馈过这个bug，能麻烦加群我们详细了解一下吗 顺便建议移出折叠，界面才会正常显示噢

一直是这样的。我没有在用 QQ 😂,而且我也只是发现了这个现象，提供不了其他的信息了。折叠有尝试移出，但是依然会有这个现象。应该是没有影响的。

**Comment by lwt-414** [comment]
尝试重装过吗

**Comment by lwt-414** [comment]
你尝试一下卸载重装吧，我们这边实在没办法复现这个问题也没有收到过相同问题反馈，如果可以还是要想办法能通过远程协助之类的看看问题出现在哪，才有办法调

**Comment by breathiness** [comment]
> 你尝试一下卸载重装吧，我们这边实在没办法复现这个问题也没有收到过相同问题反馈，如果可以还是要想办法能通过远程协助之类的看看问题出现在哪，才有办法调

我在家里的两台电脑都试了一下也没办法复现。只有公司的电脑会有这个问题。明天重装一下，不行的话就算了。其实影响也不是很大

**Comment by lwt-414** [comment]
好的，如果有相同情况我能远程的用户，应该可以改出来，到时候再跟你说一声
如果重装后ok，也麻烦跟我说一下呀

**Comment by breathiness** [comment]
> 好的，如果有相同情况我能远程的用户，应该可以改出来，到时候再跟你说一声 如果重装后ok，也麻烦跟我说一下呀

好的，主要是我这是公司的电脑，不支持远程。
刚刚试着重装了，现在开大图一直转圈，加载不出来

**Comment by lwt-414** [comment]
啊，不太应该呀，我再看看有没有遇到同样情况的
