### ISSUE TITLE
安装包更新通知打开一次插件跳一次

### ISSUE THREAD

**Issue by Yjun233** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#36]
安装包更新通知打开一次插件跳一次

**Comment by lwt-414** [comment]
你目前是什么版本了？用的是什么浏览器呀？

**Comment by Yjun233** [comment]
插件版本：V3.0.10
浏览器：360极速浏览器 版本号：13.5.1060.0 内核版本：86.0.4240.198

**Comment by lwt-414** [comment]
那公告那边有提示说有版本更新吗

**Comment by Yjun233** [comment]
公告栏没有提示

**Comment by lwt-414** [comment]
方便加一下群 我可能需要远程看看

**Comment by lwt-414** [comment]
已解决：0ae1626c3117ce88e9b08c641f99a19588c15eb1
