### ISSUE TITLE
电脑长时间锁屏后，再开屏，小刻食堂的通知一次性全刷出来了

### ISSUE THREAD

**Issue by MistEO** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#38]
具体使用场景是公司的电脑，平时都是不关机的，仅锁屏。

周末 yj 发了很多春节的饼，今天周一早上一来，小刻食堂疯狂弹通知，一次性把周末积攒的所有饼都弹出来了，我一直点 x 关了一两分钟才全部关掉 orz

希望这块可以有个策略优化一下，例如过期通知就不再弹出等

**Comment by MistEO** [comment]
补充一下使用的版本：

Chrome 版本 97.0.4692.71（正式版本） （64 位）
小刻食堂 3.0.14

**Comment by lwt-414** [comment]
浏览器自动调用windows自带通知系统，通知系统拦截通知等待开电脑时一起放出
浏览器无提供相关方法，无法检测锁屏情况下关闭推送
只能在长时间关电脑，或者周年庆期间，到设置处关闭推送功能
