### ISSUE TITLE
设置页面显示优化

### ISSUE THREAD

**Issue by frospirum** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#4]
Dun-Cookie-Vue v2.1.0

Edge Chromium 91.0.864.54
拓展选项纵向滚动条有两个，导致横向滚动条被隐藏在下面不是很好找。
![图片](https://user-images.githubusercontent.com/69426492/123050209-08251280-d433-11eb-8b6b-75215b3549ca.png)
![图片](https://user-images.githubusercontent.com/69426492/123050809-aadd9100-d433-11eb-8ddd-eeb4661e61c7.png)

Chrome 91.0.4472.114
问题好像更严重了......（kiwi也有这个问题，不知道edge是怎么魔改的）
![图片](https://user-images.githubusercontent.com/69426492/123050163-fba0ba00-d432-11eb-927c-c7f4fabde02b.png)

edge的临时解决办法是使用`extension://*extentionID*//options.html`

一点小建议：感觉设置可以改成一个独立页面而不是现在的悬浮窗口，这样就不会有此类问题。

**Comment by lwt-414** [comment]
这个是独立页面呦，通过二级界面的设置进入哒
![批注 2021-06-24 121854](https://user-images.githubusercontent.com/67498817/123202072-868ebc80-d4e6-11eb-835d-a0d5cbb6e7b6.png)

**Comment by frospirum** [comment]
! 原来那里还有个按钮啊，这么说拓展选项里的设置是无效的？

**Comment by lwt-414** [comment]
是的呀
