### ISSUE TITLE
无差别 QueryParam `t` 可导致第三方站点 CDN 缓存击穿（企鹅物流受部分影响）

### ISSUE THREAD

**Issue by GalvinGao** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#40]
https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/blob/3f4d8b13cf8787b602185260f262bef863cb5c5d/src/common/util/HttpUtil.js#L6

小刻食堂此处使用的无差别加入当前时间戳强制绕过 CDN Cache 会导致大量请求直接打到企鹅物流源站，且考虑到小刻食堂这边是轮询机制，这样的机制会造成较为严重的带宽与计算资源耗尽。（并且没钱买 CDN 的高级方案于是没有 QueryParams 过滤 awa）

建议对于企鹅物流数据统计，去除等于当前时间戳的 `t` QueryParam：这边拉取的 `/api/items`, `/api/stages` 及 `/api/v2/zones` 更新速度均非常缓慢（频率与鹰角开活动一致，约 15-30d 一次更新），因此没有必要高频且忽略缓存请求。

另外，注意到使用的 API 是已于 2020.6 左右就已 Deprecate 的 V1 API，近期的迭代将移除 V1 API 支持，还请尽快迁移至 V2 API `/api/v2/items`, `/api/v2/stages`（这两个 API 的改动很小、应该稍加测试即可直接使用 V2 API）。具体的 API 文档还请参阅：
- https://penguin-stats.cn/PenguinStats/swagger/swagger-ui.html
- https://developer.penguin-stats.io/public-api/api-v2-instruction/matrix-api

**Comment by lwt-414** [comment]
不好意思，我们会在立刻取消企鹅物流获取的`t`QueryParam并尽快发布新版本以供用户更换至新版本。

不过我们这边并没有进行轮询企鹅物流，这里是在开启电脑后，插件自动启动的时候获取一次关于关卡，资源等信息。用户在选择材料进行查看的时候获取材料具体掉率。并且将这个掉率存储下来，如果电脑没用关机，下次打开这个材料的时候不会再对接口进行请求，会直接获取本地存取的材料掉率。

非常感谢提醒我们对于接口版本的移除，这边也会进行迭代和测试，谢谢

**Comment by GalvinGao** [comment]
> 不好意思，我们会在立刻取消企鹅物流获取的`t`QueryParam并尽快发布新版本以供用户更换至新版本。
> 
> 不过我们这边并没有进行轮询企鹅物流，这里是在开启电脑后，插件自动启动的时候获取一次关于关卡，资源等信息。用户在选择材料进行查看的时候获取材料具体掉率。并且将这个掉率存储下来，如果电脑没用关机，下次打开这个材料的时候不会再对接口进行请求，会直接获取本地存取的材料掉率。
> 
> 非常感谢提醒我们对于接口版本的移除，这边也会进行迭代和测试，谢谢

感谢回复~ 昨晚又细查了下影响情况，比我们以为的好一些x 没有那么严重，这边的请求数大概占据全天请求量的 0.5%-1% 所以问题不是很大，不好意思昨天晚上有点急用词可能有点过重x

**Comment by lwt-414** [comment]
已在这个commit进行更改 82162419123800e57999b0bf4e8ff0929d491ec0

**Comment by lwt-414** [comment]
全平台（edge，火狐，chrome）已发布并过审V3.1.0，包含此问题的修复
