### ISSUE TITLE
取消勾选“推送重复的饼”后依然会接受重复饼

### ISSUE THREAD

**Issue by Yjun233** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#43]
![360截图20220310150522938](https://user-images.githubusercontent.com/67272072/157607639-d45fd7c3-462c-474c-af54-ab553d5d5e5f.png)

设置里是取消勾选了的

浏览器：360极速浏览器X
Chromium内核版本：95.0.4638.69

**Comment by lwt-414** [comment]
因为微博的消息“#明日方舟#”后面有一个空格，B站没有，所以判断两条消息不相等
暂不做处理，后续会上更可靠的比较方法

**Comment by lwt-414** [comment]
7c0a799fe5e1865570742d9388e74c2c492f3ac2
微调了一下，这次这种情况可以解决，之后再大改
