### ISSUE TITLE
希望添加wan顽子的消息

### ISSUE THREAD

**Issue by DaisenSun** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#47]
wan顽子是鹰角的社区运营，其每周更新的二创视频推荐下方会附加彩蛋，这就有了推送的价值，希望可以作为可选项添加到蹲饼系统中

**Comment by lwt-414** [comment]
这边暂时无法加入数据源，如果添加饼来源就必须大幅度降低蹲饼频率以换取更多的数据源
目前已经对如一拾山，朝陇山这些降低很大幅度频率，但也已经到达极限。
目前打算，将把wan子推荐视频放于手机端app内的一个界面中进行展示和跳转

**Comment by lwt-414** [comment]
app已经添加，如有需要通过readme找到qq群，加群参与内测
