### ISSUE TITLE
鹰角旗下重力井动画工作室

### ISSUE THREAD

**Issue by ZIDOUZI** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#48]
望适配

**Comment by lwt-414** [comment]
目前暂不考虑适配，如果添加饼来源就必须大幅度降低蹲饼频率以换取更多的数据源
目前已经对如一拾山，朝陇山这些降低很大幅度频率，但也已经到达极限。
现在正在开发app相关内容，等发布正式版后会对查件单频率进行优化，到时候再进行加入。
