### ISSUE TITLE
可以接qq机器人在群内自动发饼吗

### ISSUE THREAD

**Issue by tangjor** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#49]

**Comment by lwt-414** [comment]
小刻食堂插件端为本地蹲饼，目前无法对接qq机器人，如果有服务端也暂不考虑提供公开接口。如有能力允许使用小刻食堂源代码自行更改对接，但需要表明出处。
也可以去看看组内成员felinae98做的蹲饼机器人 https://github.com/felinae98/nonebot-bison ，如果需要可自行部署

**Comment by tangjor** [comment]
谢谢大佬

洛梧藤 ***@***.***> 于 2022年5月16日周一 下午8:28写道：
