### ISSUE TITLE
对于企鹅物流搜索功能的问题

### ISSUE THREAD

**Issue by vic233333** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#50]
1. 如图：黑暗模式下企鹅物流搜索界面下方文字颜色错误
<a href="https://imgtu.com/i/OomUSI"><img src="https://s1.ax1x.com/2022/05/18/OomUSI.png" alt="OomUSI.png" border="0" /></a>
2. 企鹅物流搜索提示文字描述不太清晰，容易引发歧义，比如理解为输入“材料名 材料名@查找企鹅物流数据”，建议改为“输入“@@”以查找企鹅物流数据”

**Comment by lwt-414** [comment]
收到，将于下版本适配

**Comment by lwt-414** [comment]
此版本 7d57506e116bb70c004c20f3cd41e7d9e28458db 已修复
并且顺便修复了不应该出现的滚动条
