### ISSUE TITLE
泰讯新域名问题

### ISSUE THREAD

**Issue by Baka632** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#56]
扩展内部使用的是泰讯的[旧域名](https://arknightscommunity.drblack-system.com)，现在已经无法访问
![image](https://user-images.githubusercontent.com/48171809/182979434-9ec19fb7-26cb-4747-b878-b191cb2bf822.png)
我们应当使用[新的域名](https://terrach.net)
![image](https://user-images.githubusercontent.com/48171809/182979507-6d954147-66dd-41d2-a306-d5c00617939f.png)
以上。

**Comment by phidiaLam** [comment]
ok，公告区域的马上换，第三方跳转下版本换

**Comment by phidiaLam** [comment]
已与 925254cad4bdd7a516d545dfb2f20d3292ab3119 更换
下个版本发布
