### ISSUE TITLE
希望可以通过鼠标滚轮控制走马灯滚动

### ISSUE THREAD

**Issue by YoungHector** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#57]
### 问题
您好，小刻食堂插件端目前只能通过鼠标点击走马灯右侧的窄条（真的很窄）来查看对应内容。

### 需求
希望可以加入鼠标滚轮手动控制走马灯滚动的功能。

感谢各位开发者的辛勤付出！

**Comment by phidiaLam** [comment]
已于这个commit 4c8fdc3e6401204b4a5074d47c4acfb28c3c9f17 完成
下个版本发布
