### ISSUE TITLE
页面弹出来的提示太快了

### ISSUE THREAD

**Issue by Chunbear** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#6]
能不能时间长一点哦，现在鼠标放上去就马上有，加个一秒左右延迟也行啊

**Comment by Yun-Shan** [comment]
(怎么在这也能见到你
是设置页面的悬浮提示吗，那个最新版应该已经改成1秒了，可以更新一下

**Comment by LiuZiYang1** [comment]
> (看到头像愣了一下然后抬头看了一眼仓库名
> 是设置页面的悬浮提示吗，那个最新版应该已经改成1秒延时了，可以更新一下
> (今天刚发布的，好像只有火狐过审了，其它浏览器得在github下载或者等过审)

他这个头像是谁啊

**Comment by Chunbear** [comment]
> (看到头像愣了一下然后抬头看了一眼仓库名
> 是设置页面的悬浮提示吗，那个最新版应该已经改成1秒延时了，可以更新一下
> (今天刚发布的，好像只有火狐过审了，其它浏览器得在github下载或者等过审)

哈哈哈哈哈哈哈 感谢！
