### ISSUE TITLE
上栏中字体过大导致显示不完全的问题

### ISSUE THREAD

**Issue by vic233333** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#68]
[![vzlJnx.png](https://s1.ax1x.com/2022/09/16/vzlJnx.png)](https://imgse.com/i/vzlJnx)

如图，上栏中文字已经超过了边框

建议：调整字体大小，或者修改上栏高度，或者使字体可以自动调整大小

**Comment by phidiaLam** [comment]
已修复，请查看

**Comment by vic233333** [comment]
非常感谢，辛苦了
