### ISSUE TITLE
[FeatureRequest]在浏览器内打开饼

### ISSUE THREAD

**Issue by sino1641** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#72]
RT，请问能否做到像右下角通知那种直接在浏览器内打开？
如果是在插件弹窗跳转的话，只能在单独的窗口打开，看不到网址（雾，其实是想要看到网址
在插件设置里也找不到相关的选项。
好奇现在的做法是插件的安全机制限制还是其他原因？
期待解答，谢谢。

**Comment by phidiaLam** [comment]
这个主要考虑的是列表打开的时候使用单独窗口打开，这样子可以不会关闭弹窗，才不会刷一半等等需要重新刷到刚刚的位置
以及希望使用我们内置的图片分享与文字分享进行分享转发（在每个饼的右上角那两个按钮）

**Comment by phidiaLam** [comment]
对了，右下角通知的点击确实是浏览器打开呀。只有列表里面的跳转是独立窗口打开吧

**Comment by sino1641** [comment]
> 对了，右下角通知的点击确实是浏览器打开呀。只有列表里面的跳转是独立窗口打开吧

对哒 桌面通知确实是浏览器打开，但是有时没来得及看，后续在弹窗里找就只能小窗打开。
~~或者换个问法，小窗打开能不能带地址栏之类的~~

**Comment by phidiaLam** [comment]
对的，这是我们设计原因。这个考虑到是上述两个原因：

**Comment by sino1641** [comment]
好哒！谢谢解答
这边试试用分享功能~

**Comment by phidiaLam** [comment]
> 好哒！谢谢解答 这边试试用分享功能~

嗯嗯，目前考虑wb有图片的分享不了，wb做了防盗链。之后会做图片获取失败只通过文字生成图片
