### ISSUE TITLE
取消窗口模式检测大小弹出过小提示

### ISSUE THREAD

**Issue by phidiaLam** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#73]

**Comment by Yun-Shan** [comment]
已经忘了这个改过没有，补充一下详细信息？

**Comment by JackieLouis** [comment]
![image](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/46364480/74b6dcbf-0d82-401c-a11f-c3392446每次点击都会出现这个

**Comment by JackieLouis** [comment]
> 已经忘了这个改过没有，补充一下详细信息？

每次点击都会出现这个
![image](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/46364480/227aeb5a-3664-42cd-b611-581535020f93)

**Comment by Yun-Shan** [comment]
> > 已经忘了这个改过没有，补充一下详细信息？
> 
> 每次点击都会出现这个 ![image](https://user-images.githubusercontent.com/46364480/276855626-227aeb5a-3664-42cd-b611-581535020f93.png)

好的 了解了

**Comment by Yun-Shan** [comment]
> > 已经忘了这个改过没有，补充一下详细信息？
> 
> 每次点击都会出现这个 ![image](https://user-images.githubusercontent.com/46364480/276855626-227aeb5a-3664-42cd-b611-581535020f93.png)

方便提供一下浏览器类型和版本吗 @JackieLouis

**Comment by JackieLouis** [comment]
> > > 已经忘了这个改过没有，补充一下详细信息？
> > 
> > 
> > 每次点击都会出现这个 ![image](https://user-images.githubusercontent.com/46364480/276855626-227aeb5a-3664-42cd-b611-581535020f93.png)
> 
> 方便提供一下浏览器类型和版本吗 @JackieLouis

星愿浏览器
当前版本 8.9.1000.2306 ( Chromium: 98.0.4758.139 Res: 2306.598 ) （64 位）
