### ISSUE TITLE
为何从插件打开网页, 只能跳转小窗口, 而不是浏览器内新选项卡？

### ISSUE THREAD

**Issue by chikinrais** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#75]
如题, 能不能追加一个功能, 打开网页的时候在浏览器当前页面的新选项卡中打开？
独立小窗各方面不太方便

**Comment by phidiaLam** [comment]
https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/issues/72

**Comment by phidiaLam** [comment]
> #72

具体原因可以看看这个pr呀

**Comment by chikinrais** [comment]
看了, 但是并未解决问题
我个人因为主要和海外博士交流, 所以需要"随时能看到地址栏"或者能“直接复制原地址（不附带其他信息）”, 
这样我才可以用它来提供网页地址这个本来的信息源
我并不介意会因此导致关闭弹窗
请问这种情况下有什么解决方案吗
