### ISSUE TITLE
chrome版插件的系统通知没有声音

### ISSUE THREAD

**Issue by chikinrais** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#76]
如题, firefox版有提示音, 但是chrome版没有
都是推送到windows系统里的通知

**Comment by phidiaLam** [comment]
您好，是win10还是win11呢，我这边测试是没问题的，都有声音。我们调用的是系统通知，也麻烦确定一下系统通知设置那边有把火狐的声音打开噢

**Comment by chikinrais** [comment]
系统是win10, 已经确认系统通知设置是开着的
chrome通过其他手段推送会有提示音, 但是插件推送的没有
firefox两边都有

**Comment by chikinrais** [comment]
https://www.bennish.net/web-notifications.html

这是我自己找到的一个在线的测试器
用它推送的通知在chrome和firefox都有提示音

**Comment by phidiaLam** [comment]
我这边试还是有，你试一个东西。到扩展页面，点击背景页，上面第二个选择控制台，英文console。然后输入`PlatformHelper.Notification.create("1", "2", "3")`，看看有没有声音？

**Comment by chikinrais** [comment]
试了, 这个有声音

**Comment by phidiaLam** [comment]
代码里用的就是这个方法，我觉得有一种可能是，微博没有推送，不是没有声音。微博图片后来做了跨域处理，导致推送的时候会报错。这个修是修了，但是没发版，最近都在准备app1.0，到时候会一起发。差不多7月中到8月

**Comment by phidiaLam** [comment]
具体你可以看看其他数据源，比如官网，游戏公告，b站，音乐这些有没有推送，有没有声音

**Comment by chikinrais** [comment]
可是B站的推送也没有声音啊
我的问题在于, firefox版是有声音的

**Comment by phidiaLam** [comment]
firefox推送是排除图片的，所以一定能推送成功

**Comment by chikinrais** [comment]
那现在除了等官方发东西以外有什么方式可以测试官方推送吗

**Comment by phidiaLam** [comment]
没有了，只能等。但是我保证刚刚那个有声音，那推送就有声音。要注意一下微博是不会推送的，也不会出现在通知栏，其他平台的是会推送的。等两天观察一下？有问题只能远程调试了。

**Comment by phidiaLam** [comment]
对啦，顺便不要两个浏览器一起蹲饼呀，会被ban掉蹲不到饼

**Comment by chikinrais** [comment]
微博不会推送是现在的bug吗还是本来就没有实时推送
又或者是微博api没法推送？

**Comment by phidiaLam** [comment]
是因为图片微博做特殊处理，你看列表里面，微博图片也显示不出来。在推送的时候会报错，导致还没推送出来就因为报错导致推送方法终止。这个我们后面做了保底的推送，让它图片失败只推送文字。但是还没有发版
7月中到8月会跟app1.0和桌面端1.0一起发布

**Comment by phidiaLam** [comment]
或者你加群，我给你个安装包？

**Comment by chikinrais** [comment]
那么现在的推送只有微博以外的平台吗

**Comment by phidiaLam** [comment]
是的

**Comment by chikinrais** [comment]
我加个群吧

**Comment by phidiaLam** [comment]
> 我加个群吧
362860473
