### ISSUE TITLE
系统设置-饼来源 栅格化

### ISSUE THREAD

**Issue by Yanstory** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#88]
饼来源太多了，现有的布局看着非常混乱

目前的想法是通过Element UI自己的栅格系统来规范显示（一行6个）：
```vue
<el-checkbox-group v-model="selectDataSource" class="checkbox-group-area" :min="1">
    <el-row :rowContainCnt="6" v-for="gno in defSourcesList.length/rowContainCnt">
      <el-col v-for="gindex in rowContainCnt" :span="24/rowContainCnt" :source="defSourcesList[(gno-1)*rowContainCnt+gindex]">
        <el-checkbox :key="source.idStr" :label="source.idStr">
          <span class="checkbox-area">
            <img class="icon-img" :src="source.icon" />
            {{ source.name }}
          </span>
        </el-checkbox>
      </el-col>
    </el-row>
</el-checkbox-group>
```

由于奇怪的问题我无法自行调试（执行npm install一段时间后CPU和硬盘占用激增，之后部分文件夹返回-4048错误，node_module安装失败），只能通过issue方式提供想法了

**Comment by phidiaLam** [comment]
嗯嗯，收到，是个好提议！不过这个适配起来不是很好，屏幕小点就会重叠。
![{41A37BD5-F107-4084-97E5-E7AB2085AFBE}](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/67498817/b2d6785f-defc-4026-9a3d-ea30e288b4b6)
![{1E23868F-63DC-49da-8313-9983CA587E85}](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/67498817/dbafd643-da1d-42f9-a23b-57b749dd5eb4)
后面可能会用分平台什么的来优化这个问题
你没办法本地install是因为我们用到了私有包，所以你可能下载不下来
