### ISSUE TITLE
[Feature Request] 饼来源分类显示

### ISSUE THREAD

**Issue by SherkeyXD** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#89]
各组放在小方格内，这样可以提升一点可读性（？
比如 明日方舟公告为一组 明日方舟版本一组 然后同一个账号的官网，B站和微博放在一组

**Comment by SherkeyXD** [comment]
但是感觉这样小屏幕的适配会是灾难（

**Comment by phidiaLam** [comment]
嗯，是有打算分组，分组跟我们 后端数据设计有关，目前手机端就是分组的。

**Comment by phidiaLam** [comment]
> 目前手机端就是分组的。

主要分成，明日方舟游戏内，明日方舟网站，微博，b站，网易云五个组
