### ISSUE TITLE
更新到4.0.1版本后工具栏图标无反应

### ISSUE THREAD

**Issue by DarkXelNaga** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#91]
旧版本火狐88.0.1在将小刻食堂更新至4.0.1及4.0.2版本后，工具栏的小刻食堂图标点击不再出现悬浮窗
回滚至3.4.3后恢复正常

**Comment by Yun-Shan** [comment]
非常抱歉，由于使用了一些较新的特性，可能不兼容旧版本的浏览器，您可以尝试更换新版本的浏览器。
