### ISSUE TITLE
Firefox 商店下载 没有信息源 一直提示更新

### ISSUE THREAD

**Issue by Fuynkio** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#95]
![图片](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/50935992/28c1c2b4-f744-402a-863e-b8e8f532ba2f)
![图片](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/50935992/39dd926e-4c47-4bb8-93cf-6ea27d205e88)
![图片](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/50935992/4f255d52-edc8-415e-8507-d67069df729a)

**Comment by Yun-Shan** [comment]
非常抱歉，因为服务器炸了，插件端由于无法获取版本信息就固定提示更新了，服务器正在抓紧抢修中，再次抱歉！

**Comment by Fuynkio** [comment]
23点查看好了 先关了省的有误解
