### ISSUE TITLE
似乎会导致edge浏览器关闭异常

### ISSUE THREAD

**Issue by Ptilopsis01** [Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue#99]
更新到最新的小刻食堂后发现edge浏览器关闭后仍然会有大量后台留存和内存占用（未开启edge中加速启动的相关功能），关闭小刻食堂后恢复正常

**Comment by Yun-Shan** [comment]
您好，你可以在地址栏输入`edge://settings/?search=后台`，然后滚动到最下方找到`在 Microsoft Edge 关闭后继续运行后台扩展和应用`，关闭该选项即可

**Comment by Ptilopsis01** [comment]
> 您好，您可以在地址栏输入`edge://settings/?search=后台`，然后滚动到最下方找到`在 Microsoft Edge 关闭后继续运行后台扩展和应用`，关闭该选项即可

这个选项我本来就没开

**Comment by phidiaLam** [comment]
> > 您好，您可以在地址栏输入`edge://settings/?search=后台`，然后滚动到最下方找到`在 Microsoft Edge 关闭后继续运行后台扩展和应用`，关闭该选项即可
> 
> 这个选项我本来就没开

![image](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/67498817/efa3c0c9-0aa3-4ed5-993a-1e446784c512)
那您看看在状态栏那边有没有个edge的标志，然后右键会显示出这样子的内容

**Comment by Ptilopsis01** [comment]
> > > 您好，您可以在地址栏输入`edge://settings/?search=后台`，然后滚动到最下方找到`在 Microsoft Edge 关闭后继续运行后台扩展和应用`，关闭该选项即可
> > 
> > 
> > 这个选项我本来就没开
> 
> ![image](https://user-images.githubusercontent.com/67498817/274604129-efa3c0c9-0aa3-4ed5-993a-1e446784c512.png) 那您看看在状态栏那边有没有个edge的标志，然后右键会显示出这样子的内容

状态栏没有任何edge的图标；而且这个问题也不是每次都一定能复现，但是关了小刻食堂就会恢复正常

**Comment by phidiaLam** [comment]
> > > > 您好，您可以在地址栏输入`edge://settings/?search=后台`，然后滚动到最下方找到`在 Microsoft Edge 关闭后继续运行后台扩展和应用`，关闭该选项即可
> > > 
> > > 
> > > 这个选项我本来就没开
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/67498817/274604129-efa3c0c9-0aa3-4ed5-993a-1e446784c512.png) 那您看看在状态栏那边有没有个edge的标志，然后右键会显示出这样子的内容
> 
> 状态栏没有任何edge的图标；而且这个问题也不是每次都一定能复现，所以我也不是很确定是不是小刻食堂的问题

那麻烦提供一下以下这些的截图，以方便我们进行排查：
1. edge的系统与性能设置 `edge://settings/system`
2. 任务管理器的资源占用
以及说明一下，edge的版本号
麻烦啦！

**Comment by Ptilopsis01** [comment]
> > > > > 您好，您可以在地址栏输入`edge://settings/?search=后台`，然后滚动到最下方找到`在 Microsoft Edge 关闭后继续运行后台扩展和应用`，关闭该选项即可
> > > > 
> > > > 
> > > > 这个选项我本来就没开
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/67498817/274604129-efa3c0c9-0aa3-4ed5-993a-1e446784c512.png) 那您看看在状态栏那边有没有个edge的标志，然后右键会显示出这样子的内容
> > 
> > 
> > 状态栏没有任何edge的图标；而且这个问题也不是每次都一定能复现，所以我也不是很确定是不是小刻食堂的问题
> 
> 那麻烦提供一下以下这些的截图，以方便我们进行排查：
> 
> 1. edge的系统与性能设置 `edge://settings/system`
> 2. 任务管理器的资源占用
> 
> 以及说明一下，edge的版本号 麻烦啦！

![image](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/93318731/77bd6cac-e7a4-4756-9ccc-c6bf96340803)
![image](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/93318731/a9078917-e145-4da1-8e08-32512ae2d76d)
版本号为 117.0.2045.60

**Comment by phidiaLam** [comment]
![2a5a0e63d1189e2c3be211b031757836](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/67498817/13b6f4c6-04e1-4b99-903a-14ed7b2b8e87)
![41577a1d02bf4315b5576c56d3ff8fbe](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/67498817/76765ec7-b97b-47d4-8341-f7a2d1a27ec4)
那再看看小刻食堂占用内存？我们这边也在尝试复现中

**Comment by phidiaLam** [comment]
顺便再次检查一下有没有在双屏或者什么之类可能漏关的edge？我们这边看到您后台有23个网页看着，一个小刻食堂不可能有23个网页，挺奇怪的

**Comment by Ptilopsis01** [comment]
> 顺便再次检查一下有没有在双屏或者什么之类可能漏关的edge？我们这边看到您后台有23个网页看着，一个小刻食堂不可能有23个网页，挺奇怪的

十几MB吧，进程多是因为其他插件也是启用状态，也就是edge本身没有正常关闭，只是关掉了前台窗口，但我最近更新的只有小刻食堂的插件和edge本身，所以我也不太清楚到底是哪边的问题

**Comment by phidiaLam** [comment]
![{D151B361-2551-49ad-85EE-0F800BE36EA8}](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/67498817/9743d97e-42c0-4400-8ce4-a0e0bffd0516)
你有没有kn可能是有看上去不是浏览器，但是实际是浏览器的开着了

**Comment by phidiaLam** [comment]
![image](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/67498817/7d2dc82f-821f-4618-9bf1-b5d5b3831d27)

把这个展开看看？是什么东西还在？完全展开噢

**Comment by Ptilopsis01** [comment]
> ![image](https://user-images.githubusercontent.com/67498817/274640046-7d2dc82f-821f-4618-9bf1-b5d5b3831d27.png)
> 
> 把这个展开看看？是什么东西还在？完全展开噢

![image](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue/assets/93318731/e57890eb-978c-40d8-962f-68f870aa2b12)

**Comment by phidiaLam** [comment]
这边两三个组员用了win10和win11尝试复现都复现不出来。可能无能为力帮你解决了，不好意思
或者您如果能给出稳定复现的方法也可以
顺带一提，你这里面的边栏呈现器和子帧比较特殊，我们复现的时候并没有看到这个，子帧查了一下是用于广告用的，不应该出现在这边

**Comment by Ptilopsis01** [comment]
> 这边两三个组员用了win10和win11尝试复现都复现不出来。可能无能为力帮你解决了，不好意思 或者您如果能给出稳定复现的方法也可以 顺带一提，你这里面的边栏呈现器和子帧比较特殊，我们复现的时候并没有看到这个，子帧查了一下是用于广告用的，不应该出现在这边

我好像破案了，这几个进程是windows copilot用的，就是copilot导致的edge无法完全关闭

**Comment by phidiaLam** [comment]
> > 这边两三个组员用了win10和win11尝试复现都复现不出来。可能无能为力帮你解决了，不好意思 或者您如果能给出稳定复现的方法也可以 顺带一提，你这里面的边栏呈现器和子帧比较特殊，我们复现的时候并没有看到这个，子帧查了一下是用于广告用的，不应该出现在这边
> 
> 我好像破案了，这几个进程是windows copilot用的，就是copilot导致的edge无法完全关闭

好的，解决就好
